name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build the Docker image
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          echo "Starting login"
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          echo "Login succesful"

      - 
        name: Build docker image
        run: |
          echo "Building docker image"
          docker build -t juandavidrobles/curso-docker-graphql:0.0.1 .
          echo "Docker image built"

      - 
        name: Docker image push
        run: |
          echo "Pushing image to Docker hub"
          docker push juandavidrobles/curso-docker-graphql:0.0.1
          echo "Image pushed to Docker hub"



        

