name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build the Docker image
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

      - name: Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          echo "Starting login"
          docker login -u $DOCKER_USER --password-stdin $DOCKER_PASSWORD
          echo "Login succesful"
